<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FlashQueue.Application\FlashQueue.Application.csproj" />
    <ProjectReference Include="..\FlashQueue.Contracts\FlashQueue.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Npgsql.DependencyInjection" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\Migrations\*.sql" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

</Project>
