<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FlashQueue.Application\FlashQueue.Application.csproj" />
    <ProjectReference Include="..\FlashQueue.Contracts\FlashQueue.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

</Project>
