<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <UserSecretsId>dotnet-FlashQueue.Consumers.Payments-3f9c5b4e-6a3e-4b7a-9b3f-7e2f1a6c9d10</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlashQueue.Contracts\FlashQueue.Contracts.csproj" />
    <ProjectReference Include="..\FlashQueue.Infrastructure\FlashQueue.Infrastructure.csproj" />
  </ItemGroup>

</Project>
